### ISSUE TITLE
BUG: Deselect not scoped to user

### ISSUE THREAD

**Issue by twmulloy** [dlhinkley/scrum-poker#7]
https://github.com/dlhinkley/scrum-poker/blob/c04cd536a40dc620abc3364febe442fd10c05e23/src/app/play/play.component.ts#L75

This call introduced a bug, it clears all set points by all users. Intended for it to be scope to the user.

**Comment by twmulloy** [comment]
I have insufficient firebase permissions to run app locally, but I think a fix could be to replace the line above with something to this effect.

`this.databaseService.setPoints(this.user.docId, null as any);`

**Comment by dlhinkley** [comment]
Very close.  it needed setPoints to -1 if toggling to off.  Should be fixed in the latest build
